### ISSUE TITLE
BcdPrefixer - decodeLength Issue

### ISSUE THREAD

**Issue by jfduran7** [sitb-software/jsPOS#12]
Hi! First Thanks for this library, is really useful!!

I found a problem with decodeLength function, in BcdPrefixer.js.
When "(this.nDigits + 1) / 2" is a float, the floor operation is not performed automatically, e.g.:
this.nDigits = 2 then, 
this.nDigits + 1/ 2 = 1.5,

for (let i = 0; i < **1.5** ; i++) 

1st iteration 0 < 1.5 --- true
**2nd iteration 1 < 1.5 --- true**, JS not make automatically the floor operation, unlike Java implementation, and the second iteration shouldn't be performed.

Thanks for your help!

**Comment by makexxoo** [comment]
update to 0.0.10-RELEASE

**Comment by fdg7** [comment]
Hi! I have tested the update but when I try to use shows an exception:
![captura de pantalla 2017-03-07 a la s 09 50 25](https://cloud.githubusercontent.com/assets/10718380/23664687/dadb4e12-031b-11e7-9f13-7e172f1defb4.png)
