### ISSUE TITLE
Cannot find module 'jspos' - Node.js

### ISSUE THREAD

**Issue by jfduran7** [sitb-software/jsPOS#13]
Hi! I have tested the **update 0.0.10-RELEASE** but when I try to use shows the following exception:

![captura de pantalla 2017-03-07 a la s 09 50 25](https://cloud.githubusercontent.com/assets/10718380/23668877/0babc9fc-0328-11e7-8a94-a7a792be44cd.png)

And if I get the previous version works

**Comment by jfduran7** [comment]
About the error, when I download the jspos package with npm, the **lib** folder doesn't exists.

**Comment by makexxoo** [comment]
update to 0.0.11-RELEASE
