### ISSUE TITLE
error npm install windoes?

### ISSUE THREAD

**Issue by mahalamobile** [sitb-software/jsPOS#6]
C:\Program Files\nodejs\node_modules\jspos>npm install

> jspos@0.0.8-RELEASE prepublish C:\Program Files\nodejs\node_modules\jspos
> npm run compile
> 
> jspos@0.0.8-RELEASE compile C:\Program Files\nodejs\node_modules\jspos
> babel ./src -d ./lib --ignore **tests**/*

./src doesn't exist

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\User\AppData\R
oaming\npm\node_modules\npm\bin\npm-cli.js" "run" "compile"
npm ERR! node v5.6.0
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! jspos@0.0.8-RELEASE compile: `babel ./src -d ./lib --ignore __tests__/*
`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the jspos@0.0.8-RELEASE compile script 'babel ./src -d ./lib
--ignore **tests**/_'.
npm ERR! This is most likely a problem with the jspos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel ./src -d ./lib --ignore **tests**/_
npm ERR! You can get their info via:
npm ERR!     npm owner ls jspos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\node_modules\jspos\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\User\AppData\R
oaming\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v5.6.0
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! jspos@0.0.8-RELEASE prepublish: `npm run compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jspos@0.0.8-RELEASE prepublish script 'npm run compile'.
npm ERR! This is most likely a problem with the jspos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile
npm ERR! You can get their info via:
npm ERR!     npm owner ls jspos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\node_modules\jspos\npm-debug.log

**Comment by makexxoo** [comment]
update to 0.0.9

**Comment by mahalamobile** [comment]
C:\Program Files\nodejs\node_modules\jspos>npm install

> jspos@0.0.9-RELEASE prepublish C:\Program Files\nodejs\node_modules\jspos
> npm run compile
> 
> jspos@0.0.9-RELEASE compile C:\Program Files\nodejs\node_modules\jspos
> babel src -d lib --only src

src doesn't exist

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\User\AppData\R
oaming\npm\node_modules\npm\bin\npm-cli.js" "run" "compile"
npm ERR! node v5.6.0
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! jspos@0.0.9-RELEASE compile: `babel src -d lib --only src`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the jspos@0.0.9-RELEASE compile script 'babel src -d lib --on
ly src'.
npm ERR! This is most likely a problem with the jspos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src -d lib --only src
npm ERR! You can get their info via:
npm ERR!     npm owner ls jspos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\node_modules\jspos\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\User\AppData\R
oaming\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v5.6.0
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! jspos@0.0.9-RELEASE prepublish: `npm run compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jspos@0.0.9-RELEASE prepublish script 'npm run compile'.
npm ERR! This is most likely a problem with the jspos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile
npm ERR! You can get their info via:
npm ERR!     npm owner ls jspos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\node_modules\jspos\npm-debug.log

**Comment by makexxoo** [comment]
delete  package.json   "prepublish": "npm run compile"

**Comment by mahalamobile** [comment]
npm install works, but npm test fails now

thanks

C:\Program Files\nodejs\node_modules\jspos>npm install

C:\Program Files\nodejs\node_modules\jspos>npm test

> jspos@0.0.9-RELEASE test C:\Program Files\nodejs\node_modules\jspos
> babel-node **tests**/index.js

module.js:341
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\jspos__tests__\
index.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at C:\Program Files\nodejs\node_modules\jspos\node_modules\babel-cli\lib_ba
bel-node.js:161:27
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\jspos\node_modul
es\babel-cli\lib_babel-node.js:162:7)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
 npm ERR! Test failed.  See above for more details.

C:\Program Files\nodejs\node_modules\jspos>

**Comment by makexxoo** [comment]
cd jspos
babel-node **tests**/index.js
