### ISSUE TITLE
babel-node not found - test

### ISSUE THREAD

**Issue by mahalamobile** [sitb-software/jsPOS#7]
root@Ubuntu-1310-saucy-64-minimal /home/app/node_modules/jspos # npm install
npm WARN lifecycle jspos@0.0.8-RELEASE~prepublish: cannot run in wd %s %s (wd=%s) jspos@0.0.8-RELEASE npm run compile /home/app/node_modules/jspos
root@Ubuntu-1310-saucy-64-minimal /home/app/node_modules/jspos # npm test

> jspos@0.0.8-RELEASE test /home/app/node_modules/jspos
> babel-node ./**tests**/index.js

sh: 1: babel-node: not found
npm ERR! Test failed.  See above for more details.

**Comment by makexxoo** [comment]
you need install babel-cli
npm install -g babel-cli

**Comment by mahalamobile** [comment]
root@Ubuntu-1310-saucy-64-minimal /home/app/node_modules/jspos # npm install
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
jspos@0.0.9-RELEASE /home/app/node_modules/jspos
├─┬ babel-core@6.7.6
│ ├─┬ babel-code-frame@6.7.5
│ │ ├─┬ chalk@1.1.3
│ │ │ ├── ansi-styles@2.2.1
│ │ │ ├── escape-string-regexp@1.0.5
│ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ └── ansi-regex@2.0.0
│ │ │ ├── strip-ansi@3.0.1
│ │ │ └── supports-color@2.0.0
│ │ ├── esutils@2.0.2
│ │ ├── js-tokens@1.0.3
│ │ └─┬ repeating@1.1.3
│ │   └─┬ is-finite@1.0.1
│ │     └── number-is-nan@1.0.0
│ ├─┬ babel-generator@6.7.5
│ │ ├─┬ detect-indent@3.0.1
│ │ │ ├── get-stdin@4.0.1
│ │ │ └── minimist@1.2.0
│ │ ├── is-integer@1.0.6
│ │ └── trim-right@1.0.1
│ ├── babel-helpers@6.6.0
│ ├── babel-messages@6.7.2
│ ├─┬ babel-runtime@5.8.38
│ │ └── core-js@1.2.6
│ ├── babel-template@6.7.0
│ ├─┬ babel-traverse@6.7.6
│ │ ├── globals@8.18.0
│ │ └─┬ invariant@2.2.1
│ │   └── loose-envify@1.1.0
│ ├─┬ babel-types@6.7.2
│ │ └── to-fast-properties@1.0.2
│ ├── babylon@6.7.0
│ ├── convert-source-map@1.2.0
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── json5@0.4.0
│ ├── lodash@3.10.1
│ ├─┬ minimatch@2.0.10
│ │ └─┬ brace-expansion@1.1.3
│ │   ├── balanced-match@0.3.0
│ │   └── concat-map@0.0.1
│ ├── path-exists@1.0.0
│ ├── path-is-absolute@1.0.0
│ ├── private@0.1.6
│ ├── shebang-regex@1.0.0
│ ├── slash@1.0.0
│ └── source-map@0.5.3
└─┬ babel-register@6.7.2
  ├── core-js@2.2.2
  ├─┬ home-or-tmp@1.0.0
  │ ├── os-tmpdir@1.0.1
  │ └── user-home@1.1.1
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  └─┬ source-map-support@0.2.10
    └─┬ source-map@0.1.32
      └── amdefine@1.0.0

npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.7
npm ERR! path /home/app/node_modules/jspos/node_modules/.staging/jspos-ea9d55c0
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/home/app/node_modules/jspos/node_modules/.staging/jspos-ea9d55c0' -> '/home/app/node_modules/jspos'
npm ERR! enoent ENOENT: no such file or directory, rename '/home/app/node_modules/jspos/node_modules/.staging/jspos-ea9d55c0' -> '/home/app/node_modules/jspos'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.7
npm ERR! path npm-debug.log.1676829299
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.1676829299'
npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.1676829299'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/app/node_modules/jspos/npm-debug.log

**Comment by makexxoo** [comment]
delete package.json     "prepublish": "npm run compile"
